import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider, THEME_ID, createTheme } from '@mui/material/styles';

// const materialTheme = createTheme();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ThemeProvider theme={null}>
      <html lang="en">
        <body>{children}</body>
      </html>
    // </ThemeProvider>
  );
}
