name: Test and Build on Pull Request to Main from Stage
run-name: ${{ github.actor }} pull request from stage to main
on:
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    if: github.base_ref == 'main' && github.head_ref == 'stage'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install

      # Testing step (blocking)
      - name: Run Tests
        run: npm run test
        continue-on-error: false # Fail if tests fail

      # Build step (blocking)
      - name: Run Build
        run: npm run build
        continue-on-error: false # Fail if build fails
