name: Test and Lint on Pull Request to Develop
run-name: ${{ github.actor }} pull request to Develop
on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize]

jobs:
  lint-test-build:
    if: github.base_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install

      # Linting step (non-blocking)
      - name: Run Lint
        run: npm run lint

      # Testing step (blocking)
      - name: Run Tests
        run: npm run test
        continue-on-error: false # Fail if tests fail

