name: Test, Lint, and Build on Pull Request to Stage from Develop
run-name: ${{ github.actor }} pull request from develop to stage
on:
  pull_request:
    branches:
      - stage
    types: [opened, synchronize]
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  REPO_OWNER: ${{ secrets.REPO_OWNER }}
  REPO_NAME: ${{ secrets.REPO_NAME }}

jobs:
  lint-test-build:
    if: github.base_ref == 'stage' && github.head_ref == 'develop'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install

      # Linting step (non-blocking)
      - name: Run Lint
        run: npm run lint

      # Testing step (blocking)
      - name: Run Tests
        run: npm run test
        continue-on-error: false # Fail if tests fail

      # Build step (blocking)
      - name: Run Build
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false # Fail if build fails

      # Install GitHub CLI
      - name: Install GitHub CLI
        run: sudo apt-get install gh

      # Auto-merge PR if tests and build succeed
      - name: Auto-Merge PR
        if: success() # This ensures the step only runs if all previous steps succeeded
        run: gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token to authenticate with the CLI
